# Generated by Django 3.2 on 2022-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_height', models.PositiveIntegerField()),
                ('url_width', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
    ]
